import type { Metadata } from 'next'
import { Container } from "@chakra-ui/react"
import Provider from './providers'
import Navbar from './navbar'

export const metadata: Metadata = {
  title: 'Test',
  description: 'Generated by your mother',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <body>
        <Provider>
          <Container maxW="900px">
            <Navbar />
            { children }
          </Container>
        </Provider>
      </body>
    </html>
  )
}
