import type { Metadata } from 'next'
import { Rubik, /* Inter */ } from 'next/font/google'
import { Container } from "@chakra-ui/react"
import Provider from './providers'
import Navbar from './navbar'


const rubik = Rubik({ subsets: ['latin'], variable: '--font-rubik' })
// const inter = Inter({ subsets: ['latin'] })

const fonts = {
  rubik,
}

export const metadata: Metadata = {
  title: 'Test',
  description: 'Generated by your mother',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <body className={fonts.rubik.className}>
        <Provider>
          <Container maxW="900px">
            <Navbar />
            { children }
          </Container>
        </Provider>
      </body>
    </html>
  )
}
